// Generated by dfx deploy
export const expoEnv = {
  EXPO_PUBLIC_DFX_VERSION:'0.22.0',
  EXPO_PUBLIC_DFX_NETWORK:'playground',
  EXPO_PUBLIC_CANISTER_ID_ICP_AUTH_FRONTEND:'v3x57-gaaaa-aaaab-qadmq-cai',
  EXPO_PUBLIC_CANISTER_ID:'v3x57-gaaaa-aaaab-qadmq-cai',
  EXPO_PUBLIC_CANISTER_CANDID_PATH:'/Users/swatantramishra/react-native-expo-icp-dfinity-auth/.dfx/playground/canisters/ICP_Auth_frontend/assetstorage.did',
};
